<template>
    <div class="wrapper">
        <div class="content">
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
            <div>分类</div>
        </div>
    </div>
</template>

<script>
import BScroll from "better-scroll"
export default {
    name:"Category",
    data(){
        return {
            scroll:null
        }
    },
    mounted(){
        this.scroll=new BScroll(".wrapper",{

        })
    }
}
</script>

<style scoped>
</style>